abstract: Gracefully skip tests if missing modules
author: Sam Vilain <samv@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Test-Depends
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.0
version: 0.02
